### ISSUE TITLE
Dataset Query Not Completing

### ISSUE THREAD

**Issue by crhea93** [astroML/astroML#238] opened 2021-03-08 20:27 UTC
Hello,
 When I run the following line in python `data = astroML.datasets.fetch_sdss_galaxy_colors() `, the terminal prints out the following:

```querying for 50000 objects
SELECT TOP 50000
  p.u, p.g, p.r, p.i, p.z, s.class, s.z, s.zerr
FROM PhotoObj AS p
  JOIN SpecObj AS s ON s.bestobjid = p.objid
WHERE 
  p.u BETWEEN 0 AND 19.6
  AND p.g BETWEEN 0 AND 20
  AND s.class <> 'UNKNOWN'
  AND s.class <> 'STAR'
  AND s.class <> 'SKY'
  AND s.class <> 'STAR_LATE'```
However, it just sits on the last line and never completes.

**Comment by bsipocz** [comment] 2021-03-09 18:38
@crhea93 - thank you for the report. I could reproduce it yesterday using the SDSS site directly, it hanged similarly for the default data release, DR16, but works for older DRs (e.g. I tried DR14 and 15). However, it all seems to be resolved by today and fetching the data works as expected. 

Please let me know if you still see the issue.

Unfortunately choosing the DR is not exposed to the user API in astroML, for those cases, I would recommend to use astroquery directly.

**Closed** 2021-03-09 18:44 UTC
Labels: data, upstream
